### ISSUE TITLE
С обновлением пакета swiftmailer/swiftmailer произошли изменения.

### ISSUE THREAD

**Issue by AlexandrGordeev** [MindyPHP/Mindy_Mail#1]
Теперь надо вызывать конструктор напрямую класса Swift_Mailer, метод newInstance устарел и обратной совместимости нет.
src/Mindy/Mail/Mailer.php строка 193

**Comment by AlexandrGordeev** [comment]
```
    return new \Swift_Mailer($this->getTransport());
```

**Comment by max107** [comment]
Исправлено в 0.3
